# frozen_string_literal: true

puts 'Creating sources...'

Source.create!(
  name: 'Feynman Lectures on Physics Vol. 2',
  source_type: 'book',
  notes: 'Classic physics textbook'
)

Source.create!(
  name: 'The Goal by Eliyahu Goldratt',
  source_type: 'book',
  notes: 'Business novel about TOC'
)

Source.create!(
  name: 'Rails Guides',
  source_type: 'documentation',
  notes: 'Official Rails documentation'
)

Source.create!(
  name: 'Wikimedia Commons',
  source_type: 'website',
  notes: 'Public domain / Creative Commons images; see individual file pages for license and attribution.'
)

Source.create!(
  name: 'Project Documentation',
  source_type: 'internal',
  notes: 'docs/app_exam.md in this repository'
)

Source.create!(
  name: 'AI Engineering by Chip Huyen',
  source_type: 'book',
  notes: 'AI Engineering, Chip Huyen, O\'Reilly 2025. Chapter 2: Understanding Foundation Models (pp. 119-231).'
)

# Maths question bank sources

Source.create!(
  name: 'AQA A-Level Mathematics Paper 1',
  source_type: 'exam',
  notes: 'AQA 7357/1 — Pure Mathematics. Past papers 2018–present plus specimen. Use source_reference like "2023 Q6".'
)

Source.create!(
  name: 'AQA A-Level Mathematics Paper 2',
  source_type: 'exam',
  notes: 'AQA 7357/2 — Pure and Mechanics. Past papers 2018–present.'
)

Source.create!(
  name: 'AQA A-Level Mathematics Paper 3',
  source_type: 'exam',
  notes: 'AQA 7357/3 — Pure and Statistics. Past papers 2018–present.'
)

Source.create!(
  name: 'Cambridge STEP II',
  source_type: 'exam',
  notes: 'Cambridge Sixth Term Examination Paper II. Administered by UAT-UK. Papers 1987–present.'
)

Source.create!(
  name: 'Cambridge STEP III',
  source_type: 'exam',
  notes: 'Cambridge Sixth Term Examination Paper III. Administered by UAT-UK.'
)

Source.create!(
  name: 'Linear Algebra Done Right — Axler (4e)',
  source_type: 'book',
  notes: 'Sheldon Axler, 4th edition, Springer 2024. Undergraduate linear algebra.'
)

Source.create!(
  name: 'Principles of Mathematical Analysis — Rudin (3e)',
  source_type: 'book',
  notes: 'Walter Rudin, 3rd edition, McGraw-Hill 1976. Undergraduate real analysis.'
)

Source.create!(
  name: 'An Introduction to Probability and Statistics — Rohatgi & Saleh',
  source_type: 'book',
  notes: 'Rohatgi & Saleh, Wiley. Undergraduate probability and mathematical statistics.'
)

Source.create!(
  name: 'Claude (claude-opus-4-7, 2026)',
  source_type: 'generated',
  notes: 'Original questions generated by Claude Opus 4.7 (Anthropic), 2026. Captured per model version so attribution survives upgrades.'
)

Source.create!(
  name: 'Louis (original)',
  source_type: 'internal',
  notes: 'Hand-authored by Louis Raymond.'
)
